workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: 3.13.0
      xcode: 14.3.1
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
