//
//  Generated file. Do not edit.
//

#ifndef GENERATED_PLUGIN_REGISTRANT_
#define GENERATED_PLUGIN_REGISTRANT_

#import <Flutter/Flutter.h>

// This file is generated by Flutter. Do not edit.
// It is used to register the plugins for the Runner target.

@interface GeneratedPluginRegistrant : NSObject
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry;
@end

#endif // GENERATED_PLUGIN_REGISTRANT_
