# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network requests to Google Analytics.
# To disable this, uncomment the following line.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network requests to Google Analytics.
# To disable this, uncomment the following line.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator = '=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_value_pairs = []
  skip_line_start_symbol = "#"
  File.foreach(file_abs_path) do |line|
    line = line.strip
    next if line.empty? or line.start_with?(skip_line_start_symbol)
    separator = ':' if line.include? ':'
    key_value = line.split(separator, 2)
    generated_key_value_pairs.push([key_value[0].strip, key_value[1].strip])
  end
  generated_key_value_pairs
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
